<x-alumniadmin-dashboard>
    <x-admin.retrieve-credentials-page
        :alumni="$alumni"
        :name="$name"
        :matriculation-id="$matriculation_id"
        :temp-email="$tempEmail"
        :category="$category"
    />
</x-alumniadmin-dashboard>
