<x-alumniadmin-dashboard>
    <x-admin.upload-alumni-search-results
        :alumni="$alumni"
        :programmes="$programmes"
        :departments="$departments"
        :faculties="$faculties"
        :years="$years"
        :categories="$categories"
    />
</x-alumniadmin-dashboard>
