<x-layouts.alumni-relations-officer>
    <x-admin.retrieve-credentials-page
        embedded
        :alumni="$alumni"
        :name="$name"
        :matriculation-id="$matriculation_id"
        :temp-email="$tempEmail"
        :category="$category"
    />
</x-layouts.alumni-relations-officer>
