<x-layouts.alumni-relations-officer>
    <x-admin.upload-alumni-page
        embedded
        :programmes="$programmes"
        :departments="$departments"
        :faculties="$faculties"
        :years="$years"
        :categories="$categories"
        :show-admin-actions="false"
    />
</x-layouts.alumni-relations-officer>
